name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 5.1.1
homepage: https://github.com/cachapa/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Prevent ongoing dependency issues since this package is bundled with the Flutter SDK
  meta: '>=1.0.0 <2.0.0'
  uuid: ^4.0.0

dev_dependencies:
  lints: any
  test: any
