name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 4.0.3
homepage: https://github.com/cachapa/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # no dependencies, no problems

dev_dependencies:
  lints: any
  test: any
