name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 1.2.2
homepage: https://github.com/cachapa/crdt

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # no dependencies, no problems

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
