name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 3.0.0-pre.5
homepage: https://pub.dev/packages/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # no dependencies, no problems

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
