name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 5.0.0
homepage: https://github.com/cachapa/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.10.0
  uuid: ^4.0.0

dev_dependencies:
  lints: any
  test: any
