name: hive_crdt_lf
description: "A plugin for crdt_lf to use with Hive."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crdt_lf: ^0.7.0+1
  hive_ce: ^2.11.3

dev_dependencies:
  test: ^1.24.0

dependency_overrides:
  crdt_lf:
    path: ../crdt_lf
